# Generated by Django 5.1.3 on 2024-12-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_Model',
        ),
    ]
