# Generated by Django 5.1.3 on 2024-12-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_model',
            old_name='details',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='details',
            new_name='body',
        ),
    ]
